# Generated by Django 3.0.3 on 2020-02-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='NIC',
            field=models.CharField(default='xxxx', max_length=255),
        ),
    ]
