# Generated by Django 3.0.3 on 2020-02-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20200226_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='children',
            field=models.CharField(choices=[('Na', 'Na'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], default='Na', max_length=12),
        ),
    ]
