# Generated by Django 3.0.2 on 2020-02-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_place_of_residence_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slug',
            field=models.SlugField(blank=True, max_length=14, unique=True),
        ),
    ]
