# Generated by Django 3.0.2 on 2020-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20200210_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='marital_Status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('cohabitation', 'cohabitation')], default='single', max_length=20),
        ),
    ]
