# Generated by Django 3.0.2 on 2020-02-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20200212_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
