# Generated by Django 3.0.3 on 2020-02-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_auto_20200212_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_of_residence',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
