# Generated by Django 3.0.3 on 2020-02-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20200213_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
