# Generated by Django 3.0.3 on 2020-02-25 20:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20200214_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='NIC',
            field=models.CharField(default='xxxxx', max_length=12),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='children',
            field=models.CharField(choices=[('na', 'na'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], default='na', max_length=12),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='marital_Status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('widowed', 'widowed'), ('divorced', 'divorced'), ('cohabitation', 'cohabitation')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='11111111', max_length=8, region=None),
        ),
    ]
