# Generated by Django 3.0.3 on 2020-02-25 20:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_auto_20200226_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='11111111', max_length=128, region=None),
        ),
    ]
